/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package project.webdriver.banrisul;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
